# Default training parameters
data:
  input_path: "data.txt"
  text_column: "text"

preprocess:
  use_lemmatize: true
  tokenize: true

train:
  vector_size: 200
  window: 5
  min_count: 2
  workers: 4
  sg: 1           # 1 = skip-gram, 0 = CBOW
  epochs: 10

visualize:
  n_samples: 500
  perplexity: 30
  random_state: 42
  output_path: "reports/figures/tsne.png"
